sudo: required
services:
  - docker

before_install:
  - docker build -t rohith/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rohith/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-760852935294'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: 'AKIA3CJS6OJ7JDUIIWHL'
  secret_access_key:
    secure: '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'
